Cursor
int Cursor::x
int Cursor::y
int Cursor::resX
int Cursor::resY
int Cursor::timer
int Cursor::cTimer
int Cursor::lengthInc
int Cursor::widthInc
Direction Cursor::dir
bool Cursor::moved
Team Cursor::team
_object Cursor::objCursor
ObjectType Cursor::objSelected
Cursor::Cursor(int x, int y, int resX, int resY, int timer)
References STOPED, NONE, RED.
void Cursor::draw_cursor()
References RECTANGLE, _object::x, _object::y, _object::length, _object::width, _object::r, _object::g, _object::b, CIRCLE, _object::radius.
Referenced by MapEditor::main_loop.
void Cursor::move_cursor(ALLEGRO_KEYBOARD_STATE keyState)
References STOPED, GRID, UP, DOWN, LEFT, RIGHT, RECTANGLE, _object::x, _object::y, CIRCLE.
Referenced by MapEditor::main_loop.
int Cursor::getX()
Referenced by MapEditor::main_loop.
int Cursor::getY()
Referenced by MapEditor::main_loop.
void Cursor::setX(int x)
Referenced by MapEditor::main_loop.
void Cursor::setY(int y)
Referenced by MapEditor::main_loop.
void Cursor::change_cursor(int i)
References RECTANGLE, NONE, CIRCLE, _object::type, _object::x, _object::y, _object::length, GRID, _object::width, _object::r, _object::g, _object::b, _object::radius, RED, BLUE.
Referenced by MapEditor::main_loop.
void Cursor::change_team()
References RED, BLUE, _object::b, _object::g, _object::r.
Referenced by MapEditor::main_loop.
void Cursor::increase_object(Direction incDir)
References RIGHT, _object::length, GRID, LEFT, DOWN, _object::width, UP.
Referenced by MapEditor::main_loop.
_object Cursor::getObject(int mapX, int mapY)
References _object::x, _object::y.
Referenced by MapEditor::main_loop.
bool Cursor::object_selected()
References NONE.
Referenced by MapEditor::main_loop.