Weapons
ALLEGRO_BITMAP* Weapons::gun
Referenced by Pistol::Pistol, Rifle::Rifle, ~Weapons, draw, getWeaponTipX, getWeaponTipY.
ALLEGRO_SAMPLE* Weapons::sound
Referenced by Pistol::Pistol, Pistol::shoot, ~Weapons, play_sound.
int16_t Weapons::type
Referenced by Pistol::Pistol, Rifle::Rifle.
int16_t Weapons::x
Referenced by calculateAngle, draw, getWeaponTipX, setX, getX.
int16_t Weapons::y
Referenced by calculateAngle, draw, getWeaponTipY, setY, getY.
int16_t Weapons::radius
Referenced by calculateAngle, draw, getWeaponTipX, getWeaponTipY, setRadius.
float Weapons::angle
Referenced by Pistol::shoot, Rifle::shoot, calculateAngle, draw, getWeaponTipX, getWeaponTipY, setAngle, getAngle.
int16_t Weapons::dmg
Referenced by Pistol::Pistol, Rifle::Rifle, getDmg.
int16_t Weapons::magSize
Referenced by Pistol::Pistol, Rifle::Rifle.
int16_t Weapons::nProjectile
Referenced by Pistol::Pistol, Rifle::Rifle.
int16_t Weapons::shootTimer
Referenced by Pistol::Pistol, Rifle::Rifle, Rifle::shoot.
float Weapons::dispersion
Referenced by Pistol::Pistol, Pistol::shoot, Rifle::Rifle, Rifle::shoot.
CProjectile** Weapons::projectiles
Referenced by Pistol::shoot, Rifle::shoot, Weapons, ~Weapons, draw, getProjectiles.
Weapons::Weapons()
References projectiles, SCREEN_PROJECTILES.
Weapons::~Weapons()
References projectiles, gun, sound.
void Weapons::setX(int16_t x)
References x.
Referenced by CCharacter::move, CCharacter::colision, CCharacter::setX.
void Weapons::setY(int16_t y)
References y.
Referenced by CCharacter::move, CCharacter::colision, CCharacter::setY.
void Weapons::setRadius(int16_t radius)
References radius.
Referenced by CCharacter::CCharacter.
void Weapons::setAngle(float angle)
References angle.
Referenced by CCharacter::setWeaponAngle.
int16_t Weapons::getX()
References x.
int16_t Weapons::getY()
References y.
int16_t Weapons::getWeaponTipX()
References gun, angle, x, radius.
Referenced by Pistol::shoot, Rifle::shoot.
int16_t Weapons::getWeaponTipY()
References gun, angle, y, radius.
Referenced by Pistol::shoot, Rifle::shoot.
int16_t Weapons::getDmg()
References dmg.
Referenced by CCharacter::getWeaponDmg.
float Weapons::getAngle()
References angle.
Referenced by CCharacter::serialize.
Projectile** Weapons::getProjectiles()
References projectiles.
Referenced by CCharacter::getProjectiles.
void Weapons::play_sound(float distance)
References sound.
Referenced by CCharacter::sound_shoot.
void Weapons::calculateAngle(int mapX, int mapY, int mouseX, int mouseY)
References x, y, angle, radius.
Referenced by CCharacter::weaponAngle.
void Weapons::draw(int mapX, int mapY)
References gun, radius, x, y, angle, SCREEN_PROJECTILES, projectiles, CProjectile::draw.
Referenced by CCharacter::draw.
virtual void Weapons::shoot(ALLEGRO_MOUSE_STATE &mouseState, Connection *conn)=0
Referenced by CCharacter::shoot.