Projectile
int16_t Projectile::velocity
Referenced by CProjectile::CProjectile, Projectile, move, getVelocity.
int16_t Projectile::id
Referenced by getId.
int16_t Projectile::x
Referenced by CProjectile::draw, CProjectile::CProjectile, Projectile, move, collide, getX, setX.
int16_t Projectile::y
Referenced by CProjectile::draw, CProjectile::CProjectile, Projectile, move, collide, getY, setY.
int16_t Projectile::length
Referenced by CProjectile::draw, CProjectile::CProjectile, Projectile, getLength.
float Projectile::angle
Referenced by CProjectile::draw, CProjectile::CProjectile, Projectile, move, collide, getAngle, setAngle.
Projectile::Projectile(int16_t x, int16_t y, int16_t length, int16_t velocity, float angle)
References velocity, x, y, length, angle.
Projectile::Projectile()
int16_t Projectile::getId()
References id.
int16_t Projectile::getX()
References x.
Referenced by collide.
int16_t Projectile::getY()
References y.
Referenced by collide.
float Projectile::getAngle()
References angle.
Referenced by collide.
int16_t Projectile::getVelocity()
References velocity.
int16_t Projectile::getLength()
References length.
Referenced by collide.
void Projectile::serialize(char *buffer)
void Projectile::setX(int16_t x)
References x.
void Projectile::setY(int16_t y)
References y.
void Projectile::setAngle(float angle)
References angle.
void Projectile::move()
References velocity, angle, x, y.
Referenced by Client::main_loop.
bool Projectile::collide(Projectile *projectile, _object &object)
References angle, getAngle, x, getX, getLength, y, getY, RECTANGLE, CIRCLE.
Referenced by Client::main_loop.