CCharacter
_object CCharacter::player
int16_t CCharacter::velocity
int16_t CCharacter::id
int16_t CCharacter::dir
int16_t CCharacter::team
int16_t CCharacter::myWeapon
bool CCharacter::dead
int16_t CCharacter::xSpawn
int16_t CCharacter::ySpawn
int CCharacter::internalSpawnTimer
int CCharacter::life
Weapons* CCharacter::weapon
float CCharacter::distance(int x1, int x2)
CCharacter::CCharacter(Weapon myWeapon)
References _object::radius, GRID, STOPED, PLAYER_VELOCITY, PISTOL, RIFLE, Weapons::setRadius, _object::type, CIRCLE.
CCharacter::~CCharacter()
int16_t CCharacter::getId()
int16_t CCharacter::getX()
References _object::x.
Referenced by Client::main_loop.
int16_t CCharacter::getY()
References _object::y.
Referenced by Client::main_loop.
int16_t CCharacter::getVelocity()
int CCharacter::getLife()
_object* CCharacter::getPlayer()
Referenced by Client::main_loop.
bool CCharacter::getDead()
Team CCharacter::getTeam()
Direction CCharacter::getDir()
void CCharacter::setDir(Direction dir)
Referenced by Client::main_loop.
void CCharacter::serialize(char *buffer)
References _object::x, _object::y, Weapons::getAngle.
Referenced by Client::main_loop.
void CCharacter::draw(int x, int y)
References _object::x, _object::y, _object::radius, _object::r, _object::g, _object::b, Weapons::draw.
Referenced by Client::main_loop.
void CCharacter::move()
References UP, _object::y, DOWN, LEFT, _object::x, RIGHT, Weapons::setX, Weapons::setY.
Referenced by Client::main_loop.
void CCharacter::die()
Referenced by Client::main_loop.
bool CCharacter::tryToRevive()
References RESPAWN_TIMER, setX, setY.
void CCharacter::revive(int16_t x, int16_t y)
References setX, setY.
Referenced by Client::main_loop.
void CCharacter::damage(int dmg)
Referenced by Client::main_loop.
void CCharacter::colision(_object *objects, int n)
References _object::x, _object::length, _object::y, _object::width, _object::radius, RECTANGLE, UP, DOWN, LEFT, RIGHT, Weapons::setX, Weapons::setY, STOPED.
Referenced by Client::main_loop.
void CCharacter::setX(int16_t x)
References _object::x, Weapons::setX.
Referenced by tryToRevive, revive, Client::main_loop, Client::connect.
void CCharacter::setY(int16_t y)
References _object::y, Weapons::setY.
Referenced by tryToRevive, revive, Client::main_loop, Client::connect.
void CCharacter::setSpawnX(int16_t x)
Referenced by Client::connect.
void CCharacter::setSpawnY(int16_t y)
Referenced by Client::connect.
void CCharacter::setTeam(Team team)
References RED, _object::r, _object::g, _object::b, BLUE.
Referenced by Client::main_loop, Client::connect.
void CCharacter::weaponAngle(int mapX, int mapY, int mouseX, int mouseY)
References Weapons::calculateAngle.
Referenced by Client::main_loop.
void CCharacter::setWeaponAngle(float angle)
References Weapons::setAngle.
Referenced by Client::main_loop.
void CCharacter::shoot(ALLEGRO_MOUSE_STATE &mouseState, Connection *conn)
References Weapons::shoot.
Referenced by Client::main_loop.
int CCharacter::getWeaponDmg()
References Weapons::getDmg.
Referenced by Client::main_loop.
void CCharacter::sound_shoot(int x, int y)
References _object::x, _object::y, Weapons::play_sound.
Referenced by Client::main_loop.
Projectile** CCharacter::getProjectiles()
References Weapons::getProjectiles.
Referenced by Client::main_loop.