Configuration
FILE* Configuration::ptr
char Configuration::buffer[255][255]
char Configuration::configFile[255][255]
char Configuration::configLine[255][2][255][255][2][255]
int Configuration::configLines
int Configuration::count
bool Configuration::configChanged
void Configuration::get_word(char *, char *, int)
Configuration::Configuration()
Configuration::~Configuration()
bool Configuration::config_found(const char *)
bool Configuration::config_create(const char *)
bool Configuration::config_load(const char *)
Referenced by Client::Client, Server::Server.
bool Configuration::config_save()
bool Configuration::config_insert(const char *, const char *)
bool Configuration::config_get(char *, const char *)
Referenced by Client::Client, Server::Server.
bool Configuration::config_remove(const char *)