Client
ALLEGRO_DISPLAY* Client::display
ALLEGRO_EVENT_QUEUE* Client::event_queue
ALLEGRO_TIMER* Client::timer
ALLEGRO_MOUSE_STATE Client::mouseState
ALLEGRO_EVENT Client::ev
ALLEGRO_SAMPLE* Client::soundtrack
MenuManager* Client::menus
Connection Client::conn
Configuration Client::config
CMap Client::map
CCharacter** Client::players
_data* Client::recieverBuffer
_data Client::senderBuffer
int Client::myId
char* Client::buffer
Weapon Client::myWeapon
int Client::res_x
int Client::res_y
int Client::port
std::string Client::ip
bool* Client::moved
bool Client::storeKeys[ALLEGRO_KEY_MAX][ALLEGRO_KEY_MAX]
int Client::mapX
int Client::mapY
int Client::maxClients
Client::Client()
References Configuration::config_load, Configuration::config_get, FPS.
Client::~Client()
void Client::setWeapon(Weapon myWeapon)
Referenced by MenuManager::main_loop.
void Client::menu()
References MenuManager::main_loop.
Referenced by main.
bool Client::connect()
References Connection::create_client, Connection::event_service, Connection::event_type_receive, Connection::getPacketData, PROTOCOL_N_PEERS, _data::buffer, _data::type, PROTOCOL_MY_WEAPON, Connection::send_packet_reliable, PROTOCOL_MAP_FILE, Map::deserialize, PROTOCOL_SET_POS_TEAM, CCharacter::setX, CCharacter::setSpawnX, CCharacter::setY, CCharacter::setSpawnY, CCharacter::setTeam.
Referenced by MenuManager::main_loop.
void Client::main_loop()
References Connection::event_service, Connection::event_type_receive, Connection::getPacketData, PROTOCOL_NEW_USER, CCharacter::setX, CCharacter::setY, CCharacter::setTeam, PROTOCOL_CHARACTER, CCharacter::setDir, CCharacter::setWeaponAngle, PROTOCOL_DISCONNECT, PROTOCOL_NEW_SHOOT, CCharacter::getProjectiles, CCharacter::sound_shoot, PROTOCOL_DELETE_BULLET, PROTOCOL_REVIVE, CCharacter::revive, PROTOCOL_HIT, CCharacter::damage, CCharacter::die, Connection::event_type_disconnect, UP, DOWN, LEFT, RIGHT, STOPED, CCharacter::getX, CCharacter::getY, CCharacter::move, CCharacter::colision, CMap::getObjects, CMap::getNobject, CCharacter::weaponAngle, SCREEN_PROJECTILES, RECTANGLE, Projectile::collide, _data::type, _data::buffer, Connection::send_packet_reliable, CCharacter::getPlayer, CCharacter::getWeaponDmg, Projectile::move, CCharacter::shoot, CCharacter::serialize, Connection::send_packet_unreliable, CMap::draw_map, CCharacter::draw.
Referenced by MenuManager::main_loop.