CMap
bool CMap::drawCircles
CMap::CMap(std::string name, int max_objects, int length, int width)
References Map::max_objects, Map::length, Map::width, Map::objects, Map::n_object.
CMap::CMap()
References Map::n_object.
void CMap::new_object(_object object)
References Map::objects, Map::n_object.
Referenced by MapEditor::main_loop.
void CMap::destroy_object(int x, int y)
References Map::n_object, Map::objects.
Referenced by MapEditor::main_loop.
void CMap::draw_map(int x, int y)
References Map::n_object, Map::objects, Map::type, RECTANGLE, Map::length, Map::width, CIRCLE.
Referenced by Client::main_loop, MapEditor::main_loop.
void CMap::setDrawCircles(bool drawCircles)
Referenced by MapEditor::MapEditor.
_object* CMap::getObjects()
References Map::objects.
Referenced by Client::main_loop.
int CMap::getNobject()
References Map::n_object.
Referenced by Client::main_loop.
CMap::~CMap()
References Map::objects.