Connection
ENetAddress Connection::address
ENetHost* Connection::conn
ENetHost * Connection::connS
ENetEvent Connection::event
bool Connection::client
ENetPeer* Connection::peer
ENetAddress Connection::lastConnection
unsigned int Connection::packetLength
void* Connection::packetData
char Connection::packetBuffer[SIZE][SIZE]
int Connection::peerID
void Connection::perror(std::string error)
Connection::Connection()
Connection::~Connection()
void Connection::create_server(int port, int num_peers)
Referenced by Server::Server.
void Connection::send_packet_reliable(void *data, int size, int ID)
Referenced by Client::main_loop, Client::connect, Pistol::shoot, Rifle::shoot.
void Connection::send_packet_unreliable(void *data, int size, int ID)
Referenced by Client::main_loop.
void Connection::broadcast_packet(void *data, int size)
Referenced by Server::main_loop.
void Connection::send_flush()
int Connection::event_service(int timer)
Referenced by Client::main_loop, Client::connect, Server::main_loop.
bool Connection::event_type_connect()
Referenced by Server::main_loop.
bool Connection::event_type_receive()
Referenced by Client::main_loop, Client::connect, Server::main_loop.
bool Connection::event_type_disconnect()
Referenced by Client::main_loop, Server::main_loop.
bool Connection::create_client(std::string ip, int port)
Referenced by Client::connect.
ENetAddress Connection::getLastConnection()
unsigned int Connection::getPacketLength()
void* Connection::getPacketData()
Referenced by Client::main_loop, Client::connect, Server::main_loop.
int Connection::getPeerId()
Referenced by Server::main_loop.