IMenu
virtual void IMenu::print_menu()=0
Referenced by MenuManager::main_loop.
virtual IMenu::~IMenu()
virtual void IMenu::botao(ALLEGRO_MOUSE_STATE *mouseState)=0
Referenced by MenuManager::main_loop.
virtual int IMenu::botao_action()=0
Referenced by MenuManager::main_loop.